version: "3.7"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    container_name: crypto-knight-infra-observability-elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ulimits:
      memlock:
        soft: -1
        hard: -1
    cap_add:
      - IPC_LOCK
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    expose:
      - "9200"
    restart: always

  logstash:
    image: docker.elastic.co/logstash/logstash:8.13.4
    container_name: crypto-knight-infra-observability-logstash
    depends_on:
      - elasticsearch
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    restart: always
    ports:
      - "5044:5044"

  kibana:
    image: docker.elastic.co/kibana/kibana:8.13.4
    container_name: crypto-knight-infra-observability-kibana
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    expose:
      - "5601"
    restart: always

  prometheus:
    image: prom/prometheus
    container_name: crypto-knight-infra-observability-prometheus
    volumes:
      - prometheus-data:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    expose:
      - "9090"
    restart: always

  grafana:
    image: grafana/grafana
    container_name: crypto-knight-infra-observability-grafana
    volumes:
      - grafana-data:/var/lib/grafana
    expose:
      - "3000"
    depends_on:
      - prometheus
    restart: always

  # nginx:
  #   container_name: crypto-knight-infra-observability-nginx
  #   image: nginx:alpine
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #   depends_on:
  #     grafana:
  #       condition: service_started
  #     kibana:
  #       condition: service_started
  #     prometheus:
  #       condition: service_started
  #   restart: always

volumes:
  prometheus-data:
  grafana-data:
  elasticsearch-data:
