version: "3.9"
services:
  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: crypto-knight-infra-rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: crypto
      RABBITMQ_DEFAULT_PASS: crypto
    volumes:
      - crypto-knight-infra-rabbitmq:/var/lib/rabbitmq
volumes:
  crypto-knight-infra-rabbitmq_data:
