version: "3.9"
services:
  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: crypto-knight-infra-rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: crypto
      RABBITMQ_DEFAULT_PASS: crypto
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    # ports:
    #   - "5672:5672"
    #   - "15672:15672"
volumes:
  rabbitmq_data:
